/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.starling;

import java.net.http.HttpClient;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.starling.models.FeedItems;
import com.starling.repos.AccountsRepo;
import com.starling.repos.FeedRepo;
import com.starling.repos.SavingGoalsRepo;
import com.starling.services.AccountsService;
import com.starling.services.RoundUpService;
import com.starling.services.SavingGoalsService;
import com.starling.services.FeedService;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class App {
    private static final ObjectMapper OBJECT_MAPPER = new ObjectMapper();
    private static final Logger LOGGER = LoggerFactory.getLogger(App.class);
    private AccountsRepo accountsRepo;
    private AccountsService accountService;
    private FeedRepo feedRepo;
    private FeedService feedService;
    private SavingGoalsRepo savingsGoalsRepo;
    private SavingGoalsService savingGoalsService;

    public App(HttpClient client,
            AccountsRepo accountsRepo, AccountsService accountService,
            FeedRepo feedRepo, FeedService feedService,
            SavingGoalsRepo savingGoalsRepo, SavingGoalsService savingGoalsService) {
        this.accountsRepo = accountsRepo;
        this.accountService = accountService;
        this.feedRepo = feedRepo;
        this.feedService = feedService;
        this.savingsGoalsRepo = savingGoalsRepo;
        this.savingGoalsService = savingGoalsService;
    }

    public App(HttpClient client) {
        this.accountsRepo = new AccountsRepo(client, LOGGER);
        this.accountService = new AccountsService(accountsRepo, OBJECT_MAPPER, LOGGER);
        this.feedRepo = new FeedRepo(client, LOGGER);
        this.feedService = new FeedService(feedRepo, OBJECT_MAPPER, LOGGER);
        this.savingsGoalsRepo = new SavingGoalsRepo(client, LOGGER);
        this.savingGoalsService = new SavingGoalsService(savingsGoalsRepo, OBJECT_MAPPER, LOGGER);
    }

    public String getAccountId(String bearerToken) {
        try {
            LOGGER.info("Getting primary account ID.");
            return this.accountService.getPrimaryAccountId(bearerToken);
        } catch (Exception exception) {
            LOGGER.error("An error occurred getting primary account id: ", exception);
            throw exception;
        }
    }

    public FeedItems getFeedItems(String accountId, String weekStartInputString, String bearerToken) {
        try {
            LOGGER.info("Getting feed items.");
            return this.feedService.getFeedItems(accountId, weekStartInputString, bearerToken);
        } catch (Exception exception) {
            LOGGER.error("An error occurred getting feed items: ", exception);
            throw exception;
        }
    }

    public int calculateSavings(FeedItems feedItems) {
        try {
            return RoundUpService.calculateRoundUp(feedItems);
        } catch (Exception exception) {
            LOGGER.error("An error occurred calculating savings: ", exception);
            throw exception;
        }
    }

    public String addSavings(String accountId, int savings, String bearerToken) {
        try {
            LOGGER.info("Adding savings.");
            return this.savingGoalsService.addMoneyToSavingsGoal(accountId, bearerToken, savings);
        } catch (Exception exception) {
            LOGGER.error("An error occurred adding savings: ", exception);
            throw exception;
        }
    }

    public static void main(String[] args) {
        if (args.length < 2) {
            LOGGER.error("No arguments provided.");
            System.err.println("Please provide the week start and bearer token as a command line argument.");
            System.exit(1);
        }

        HttpClient client = HttpClient.newHttpClient();
        App app = new App(client);

        String weekStart = args[0];
        String bearerToken = args[1];

        String accountId = app.getAccountId(bearerToken);

        FeedItems feedItems = app.getFeedItems(accountId, weekStart, bearerToken);

        int savings = app.calculateSavings(feedItems);

        String response = app.addSavings(accountId, savings, bearerToken);

        System.out.println(response);
    }
}
