/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.starling;

import java.net.http.HttpClient;

import com.starling.models.FeedAmount;
import com.starling.models.FeedItem;
import com.starling.models.FeedItems;
import com.starling.services.AccountService;
import com.starling.services.FeedService;
import com.starling.services.RoundUpService;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

class AppTest {
    HttpClient client = mock(HttpClient.class);
    AccountService accountService = mock(AccountService.class);
    FeedService feedService = mock(FeedService.class);
    RoundUpService roundUpService = mock(RoundUpService.class);
    App app = new App(client, accountService, feedService);

    @Test
    void testGetAccountId() throws Exception {
        // Arrange
        when(accountService.getPrimaryAccountId(any())).thenReturn("MockAccountId");

        // Act
        String response = app.getAccountId("Mock token");

        // Assert
        assertEquals("MockAccountId", response);
    }

    @Test
    void testGetAccountIdThrows() throws Exception {
        // Arrange
        when(accountService.getPrimaryAccountId(any())).thenThrow(new RuntimeException("Mocked Error"));

        Exception exception = assertThrows(Exception.class, () -> {
            // Act
            app.getAccountId("Mock token");
        });

        // Assert
        assertEquals("Mocked Error", exception.getMessage());
    }

    @Test
    void testGetFeedItems() throws Exception {
        // Arrange
        FeedItems mockedFeedItems = createMockedFeedItems();
        when(feedService.getFeedItems(any(), any(), any())).thenReturn(mockedFeedItems);

        // Act
        FeedItems response = app.getFeedItems("MockAccountId", "2021-01-01", "MockToken");

        // Assert
        assertEquals(mockedFeedItems, response);
    }

    @Test
    void testGetFeedItemsThrows() throws Exception {
        // Arrange
        when(feedService.getFeedItems(any(), any(), any())).thenThrow(new RuntimeException("Mocked Error"));

        Exception exception = assertThrows(Exception.class, () -> {
            // Act
            app.getFeedItems("MockAccountId", "2021-01-01", "MockToken");
        });

        // Assert
        assertEquals("Mocked Error", exception.getMessage());
    }

    private FeedItems createMockedFeedItems() {
        FeedAmount feedAmount = new FeedAmount("USD", 123);
        FeedItem feedItem = new FeedItem("MockFeedItemId", "OUT", feedAmount);

        FeedItems feedItems = new FeedItems(new FeedItem[] { feedItem });

        return feedItems;
    }

}