/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.starling;

import java.net.http.HttpClient;

import com.starling.models.FeedAmount;
import com.starling.models.FeedItem;
import com.starling.models.FeedItems;
import com.starling.repos.AccountsRepo;
import com.starling.repos.FeedRepo;
import com.starling.services.AccountsService;
import com.starling.services.FeedService;
import com.starling.services.SavingGoalsService;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.*;

class AppTest {
    HttpClient client = mock(HttpClient.class);
    AccountsRepo accountsRepo = mock(AccountsRepo.class);
    AccountsService accountService = mock(AccountsService.class);
    FeedRepo feedRepo = mock(FeedRepo.class);
    FeedService feedService = mock(FeedService.class);
    SavingGoalsService savingGoalsService = mock(SavingGoalsService.class);
    App app = new App(client, accountsRepo, accountService, feedRepo, feedService, savingGoalsService);

    @Test
    void testGetAccountId() throws Exception {
        // Arrange
        when(accountService.getPrimaryAccountId(any())).thenReturn("MockAccountId");

        // Act
        String response = app.getAccountId("Mock token");

        // Assert
        assertEquals("MockAccountId", response);
    }

    @Test
    void testGetAccountIdThrows() throws Exception {
        // Arrange
        when(accountService.getPrimaryAccountId(any())).thenThrow(new RuntimeException("Mocked Error"));

        Exception exception = assertThrows(Exception.class, () -> {
            // Act
            app.getAccountId("Mock token");
        });

        // Assert
        assertEquals("Mocked Error", exception.getMessage());
    }

    @Test
    void testGetFeedItems() throws Exception {
        // Arrange
        FeedItems mockedFeedItems = createMockedFeedItems();
        when(feedService.getFeedItems(any(), any(), any())).thenReturn(mockedFeedItems);

        // Act
        FeedItems response = app.getFeedItems("MockAccountId", "2021-01-01", "MockToken");

        // Assert
        assertEquals(mockedFeedItems, response);
    }

    @Test
    void testGetFeedItemsThrows() throws Exception {
        // Arrange
        when(feedService.getFeedItems(any(), any(), any())).thenThrow(new RuntimeException("Mocked Error"));

        Exception exception = assertThrows(Exception.class, () -> {
            // Act
            app.getFeedItems("MockAccountId", "2021-01-01", "MockToken");
        });

        // Assert
        assertEquals("Mocked Error", exception.getMessage());
    }

    @Test
    void testGetSavingGoals() throws Exception {
        // Arrange
        when(savingGoalsService.addMoneyToSavingsGoal(any(), any(), anyInt())).thenReturn("Mocked Saving Goals");

        // Act
        String response = app.addSavings("MockAccountId", 99, "MockToken");

        // Assert
        assertEquals("Mocked Saving Goals", response);
    }

    @Test
    void testGetSavingGoalsThrows() throws Exception {
        // Arrange
        when(savingGoalsService.addMoneyToSavingsGoal(any(), any(), anyInt()))
                .thenThrow(new RuntimeException("Mocked Error"));

        Exception exception = assertThrows(Exception.class, () -> {
            // Act
            app.addSavings("MockAccountId", 99, "MockToken");
        });

        // Assert
        assertEquals("Mocked Error", exception.getMessage());
    }

    private FeedItems createMockedFeedItems() {
        FeedAmount feedAmount = new FeedAmount("USD", 123);
        FeedItem feedItem = new FeedItem("MockFeedItemId", "OUT", feedAmount);

        FeedItems feedItems = new FeedItems(new FeedItem[] { feedItem });

        return feedItems;
    }

}